services:
  - name: percona:8.0.16-7-centos
    alias: mysql
    command: ["--default-authentication-plugin=mysql_native_password"]

variables:
  MYSQL_DATABASE: test
  MYSQL_ROOT_PASSWORD: root
stages:
  - build
build:
  stage: build
  services:
    - mysql
  only:
    refs:
      - main
  image: klvenky/node-14-alpine-docker:latest
  script:
    - yarn --ignore-optional --pure-lockfile --prefer-offline
    - yarn test
